# Numpy 배열(ndarray, n dimension array)
### 숫자를 관리하는데 유용한 모듈

In [4]:
import numpy as np
# 아나콘다가아니라 다른곳에서 사용하면 pip install numpy로 설치#

In [2]:
# 파이썬의 list : LinkedList로 구현되어있다.(불연속적) 동작속도가 느리다
#            comma로 요소 구별. 서로 다른 자료형 사용 가능
# numpy의 배열 (ndarray) : 연속된 메모리 구조, 동작속도가 빠르다.
#            comma를 사용하지 않고 공백으로 요소 구별
#            서로 같은 자료형을 사용해야 한다.(numpy는 다른)

In [4]:
# list
list1 = [0, 1, 2, 3, 4, 5]
print(list)
print(type(list1))

# numpy의 array
a = np.array([0, 1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.dtype)

<class 'list'>
<class 'list'>
[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [6]:
# numpy의 dtype 객체의 종류
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [9]:
# int와 float --> float
a = np.array([0, 1, 2, 3, 4, 5., 'Hello'])
print(a)
print(type(a)) # numpy.ndarray
print(a.dtype)
# <U32 -> < : 리틀엔디언 U : 유니코드, 32 : 최대문자32byte
# 유니코드 인코딩 방식
# 1. EUC-KR, CP949(Ms949) : 완성형, 한글 2바이트, 영문1바이트, 윈도우에서 사용
# 2. UTF-8 : 조합형, 한글 3바이트, 영문1바이트, 리눅스에서 사용

['0' '1' '2' '3' '4' '5.0' 'Hello']
<class 'numpy.ndarray'>
<U32


In [12]:
# 배열의 데이터 타입 변환 astype
a1 = np.array(['1.234', '3.123', '4.43526', '5', '7'])
print(a1, a1.dtype)

a2 = a1.astype('float32')
print(a2, a2.dtype)

a3 = a2.astype('int32')
print(a3, a3.dtype)

['1.234' '3.123' '4.43526' '5' '7'] <U7
[1.234   3.123   4.43526 5.      7.     ] float32
[1 3 4 5 7] int32


## 차원 (dimension, Rndk) 과 Shape
* 차원 : 1, 2, 3차원, 첫 데이터까지의 대괄호의 갯수와 일치
* shpae : 차원의 요소의 수, 튜플 형식
1차원 Shape : (x, )
2차원 Shape : (x, y), matrix 행렬
3차원 Shape : (x, y, z)

In [19]:
# 1차원 배열의 Shape
# arange(start, end + 1, step)
a = np.arange(12)
print(a, type(a))
print(a.shape) # (12, )

t = a.shape
print(type(t))
print(a.shape[0])

a2 = np.arange(2, 10)
print(a2, type(a2))
print(a2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'>
(12,)
<class 'tuple'>
12
[2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
(8,)


In [23]:
# 2차원 배열의 Shape : 행row(axis = 0)과 열column(axix)
m = np.array([np.arange(3), np.arange(3)])
print(m, type(m))
print(m.shape)

m = np.array([[0, 1, 2], [0, 1, 2]])
print(m, type(m))
print(m.shape)

[[0 1 2]
 [0 1 2]] <class 'numpy.ndarray'>
(2, 3)
[[0 1 2]
 [0 1 2]] <class 'numpy.ndarray'>
(2, 3)


In [6]:
# 3차원
m = np.array([[[10, 11, 12], [13, 14, 15]], [[20, 21, 22], [23, 24, 25]], [[30, 31, 32], [33, 34, 35]]])
print(m, type(m))
print(m.shape)
print(m.shape[2])

[[[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]

 [[30 31 32]
  [33 34 35]]] <class 'numpy.ndarray'>
(3, 2, 3)
3


In [11]:
round(1.23456, 2)

1.23

In [14]:
# 배열의 shape 바꾸기 : reshape()
m1 = np.arange(12)
print(m1)
print(m1.shape)

m2 = m1.reshape(3, 4)
print(m2)
print(m2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [18]:
# -1을 사용한 reshape
m1 = np.arange(12)
print(m1, m1.shape)
m2 = m1.reshape(-1, 6) # 행의 요소수를 자동으로 계산, 2
print(m2, m2.shape)
m3 = m1.reshape(4, -1) # 열의 요소수를 자동으로 계산, 3
print(m3, m3.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)


In [20]:
# 배열의 인덱싱과 슬라이싱
# 1차원 배열의 인덱싱과 슬라이싱 : list와 동일함
d = np.arange(12)
print(d, d.shape) # [0 1 2 ...] (12, )
print(d[0], d[1])
print(d[2:8])
d[0] = 10
print(d[0])

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0 1
[2 3 4 5 6 7]
10


In [29]:
# 2차원 배열의 인덱싱과 슬라이싱
# data[행, 열]
m2 = np.arange(12).reshape(3, 4)
print(m2)
# 인덱싱
print(m2[0][0])
print(m2[0,0])
# 슬라이싱
print(m2[0])
print(m2[0,:])
print(m2[:,:-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
0
[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [33]:
# 3차원 배열의 인덱싱과  슬라이싱
# data[면, 행, 열]
m3 = np.arange(12).reshape(2, 2, 3)
print(m3, m3.shape)

# 인덱싱
print(m3[0][0][0]) # 사용잘안함
print(m3[0, 0, 0])
print(m3[0, 1, 2])
print(m3[:, :, :])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
0
0
5
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [38]:
# 불린 인덱싱 : 조건을 사용한 인덱싱, 조건 검색 필터를 사용한 추출
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a > 2)
print(a[a > 2])

boolean_index = np.array([True, False, True, False, True, True])
print(boolean_index)
print(a[boolean_index])

[1 2 3 4 5 6]
[False False  True  True  True  True]
[3 4 5 6]
[ True False  True False  True  True]
[1 3 5 6]
